version: '3.8'

services:
  client:
    build: ./client
    container_name: client
    restart: unless-stopped

  admin:
    build: ./admin
    container_name: admin
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client:/usr/share/nginx/html/client
      - ./admin:/usr/share/nginx/html/admin
    depends_on:
      - client
      - admin